[request_definition]
r = sub, dom, obj, act, sub_id, owner_id

[policy_definition]
p = sub, dom, obj, act, scope

# RBAC with domains (s)
[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && r.dom == p.dom && r.obj == p.obj && r.act == p.act && (p.scope == "any" || (p.scope == "own" && r.owner_id != "" && r.owner_id == r.sub_id))
