server {
    listen 80;
    server_name localhost;

    # Identity service
    location ~ ^/api/(auth|users)(/|$) {
        proxy_pass         http://identity:8888;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Strategy Registry service
    location ~ ^/api/strategies(/|$) {
        proxy_pass         http://strategy-registry:8888;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /connect/identity/ {
        rewrite ^/connect/identity/(.*)$ /connect/$1 break;
        proxy_pass         http://identity:8888;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /connect/strategy-registry/ {
        rewrite ^/connect/strategy-registry/(.*)$ /connect/$1 break;
        proxy_pass         http://strategy-registry:8888;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    
}
