root = "."
tmp_dir = "deploy/docker/air/tmp/strategy-registry"

[build]
  bin = "deploy/docker/air/tmp/strategy-registry/main"
  cmd = "go build -o deploy/docker/air/tmp/strategy-registry/main ./services/strategy-registry/cmd/api/main.go"
  include_ext = ["go"]
  include_dir = ["services/strategy-registry", "internal"]
  exclude_dir = [
    "vendor",
    "tmp",
    "deploy/docker/air/tmp",
    "apps",
    "docs",
    "services/identity",
    "node_modules",
  ]

[log]
  level = "debug"
